appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ZxC+5UcJa85McsAcnZHk4V4wRWUsEKeO/GWoXCcJ3mnppnDCeUk6hG7jGopdI4LlwNtjRjANTQ5D+CxGj1vg3OsVzrb39bWHcFDpxUshM7G2uGiv17/xeEmk4mbTYEN1lA2dpsC97GrDdbr8QpIbO2J8zaWQKIDQddQ9rcx2kr9HKqNMH3qj4XxffCWsBXabF+BMbb4x0isba/a7EVy5uYYEYjC/4vw9cgE414sEiIXTblQhtjIv3w2+DLDzViQqob7Ls1do2wP2e1dwCP+/7/HyOo2idosol+3H0TscM/KJiOXkTiZV7KU+Hv+8rr1+GJWEF89KmIs1Vq3HkNfg84eJhze1J4jGKwRn1j8IpXyXlwgB0udlRp2GtR1DJxgaAEEga2ZHSxj2qN9Q9ZV1RG5FQJGMkF1RVKknt9f4/a7ih7AgzY0AVy7jkBCb99L4aMS/wENxwGGLkq/sqxRpDlTRb+2J6VUZFr8oH6IrmYj+8410+41LV6iMH6VW43xfKEWKP//+jwXfqU5+5V+waQ60ar1Rgw6dgGKNSb4rOyTc0f2QTqGL3ZfoGZgMf768SnIxCtZFR59creA2Vltw6GrLInwXA8ldPSrgtmRl0EaaTg0FWHdm8rCS6U7rcWpZmAfG5OPbBBcMAmvKaGxvKmOjim9QtSwhs0f1Ks3A3xA=}
